### ISSUE TITLE
Problems loggin in

### ISSUE THREAD

**Issue by viciousviper** [erastmorgan/Mail.Ru-.net-cloud-client#2]
Hi @erastmorgan,

I'd like to use your libary to access *cloud.mail.ru* in my cloud application.
Unfortunately I can't seem to get past login because I don't have any pre-initialized cookies and thus code passes into the `else`-branch of https://github.com/erastmorgan/Mail.Ru-.net-cloud-client/blob/master/MailRuCloudApi/Account.cs#L115 which always returns `false` and leads to an `Exception("Auth token has't been retrieved.")`.
The test method `A1LoginTest()` from your very own UnitTest1 runs into pretty much the same issue and fails as well.
Can you advise on a way for me to receive a successful login?

TIA, vv

**Comment by erastmorgan** [comment]
Hi, @viciousviper , cookies can be null. Could you provide an example with your login method?

**Comment by viciousviper** [comment]
Hi @erastmorgan,

thanks for your quick response.
I tried two things:

1. Ran the unit test `A1LoginTest()` from your project - after uncommenting the relevant lines and inserting my login info. It fails in line https://github.com/erastmorgan/Mail.Ru-.net-cloud-client/blob/master/Tests/UnitTest1.cs#L22 with an `AssertFailedException` because `account.AuthToken` is `null`. Furthermore, `account.Login()` returns `false` in line 21, but this is not verified in your test.
2. In my own code, I execute `new MailRuCloud("<myLogin>", "<myPassword>")` and immediately receive the `Exception("Auth token has't been retrieved.")` as quoted in my previous post. It may be of interest that *myPassword* contains a bunch of special characters - but it is obviously acceptable to the mail.ru Web site. Looking at the code I am not surprised that the *Exception* is thrown - it is outright inevitable in the absence of cookies, and since in my case there are no cookies returned in the response I can't see how the result of `Login()` could ever be `true`.

My suspicion is that something changed in *mail.ru*'s handling of the login process since you committed your sources earlier this year.

**Comment by erastmorgan** [comment]
Hi, @viciousviper , I tested on my local environment with my login info and all works fine. If it possible, can you provide your credentials on cloud.mail.ru? and I will try to reproduce your problem to create fix. Your login info you can send me on email erastmorgan@gmail.com or if it not possible, please provide more info about special characters used in your login info.

**Comment by viciousviper** [comment]
Hi @erastmorgan,

you were totally correct, the problem is due to an overcomplicated password. Good thinking on your part.
The two passwords I tried were

- 6\A;;_`Y.nez~C-+1mUY
- 8rw@jh+T:G3+sypq=;0O

Both passwords are accepted by the *mail.ru* Web site but fail to return the required cookies from `MailRuCloudApi.Account.Login()` in your API library - probably due to an internal error somewhere behind the scenes.
Maybe you can harden your login process by HTML-escaping the password string?

Regards,
vv

**Comment by viciousviper** [comment]
A bit off-topic, but: Do you know if there is a way to determine the current free and used quota for a cloud.mail.ru account?

**Comment by erastmorgan** [comment]
Hi, @viciousviper , sorry for delay, but right now I am very busy. I will working with your issue on the weekend.

**Comment by erastmorgan** [comment]
Defect fixed by commit d318da4
