### ISSUE TITLE
Feature request: Account quota and file modification time

### ISSUE THREAD

**Issue by viciousviper** [erastmorgan/Mail.Ru-.net-cloud-client#3]
Please add the following features to your library:

- Read access to the free and used quota for a *cloud.mail.ru* account
- Read and write access to creation time and last-modified time for both files and directories

Regards
vv

**Comment by viciousviper** [comment]
I don't mean to be impolite - but could you perhaps give me an idea if you are even considering the requested features for inclusion into your library at some time in the forseeable future?
Cheers,
vv

**Comment by erastmorgan** [comment]
ok, I will try to add this feature on this week

2017-01-04 0:25 GMT+04:00 viciousviper <notifications@github.com>:

**Comment by erastmorgan** [comment]
Task completed at rev. b12a9b7 . Please check my comment in this commit

**Comment by viciousviper** [comment]
Works nicely, thank you very much. 👍
If the service doesn't expose a creation date - or even a folder modification date - then that's just the way it is.

There are, however, two or three other things I'd wish for:

- I'd like to be able to up-/download a Mail.Ru file from/to an arbitrary `System.IO.Stream` object instead of being limited to a `System.IO.File`.
- If I create a new `File` or `Folder`, I'd like to receive the created object as the method result instead of a `bool` value. Specifically, I'd like to retrieve the file hash value without another round trip via an additional `GetItems()` call. 
- I'd like to be able to remove an arbitrary object by its full path - presently, a `File` cannot be constructed with a specific `FulPath` (sic!).

If you don't object, I'll give it a shot and submit a PR later on.
