### ISSUE TITLE
Account .Login WebApp

### ISSUE THREAD

**Issue by levkin77** [erastmorgan/Mail.Ru-.net-cloud-client#7]
В новом чистом приложении MVC - не работает следующий код:
string Login = "*****@mail.ru";
Password = "******";
Account account = new Account(Login, Password);
var res = account.Login(); **// -- и все!!! далее нет не сообщений об ошибках, не выхода.. входим в бесконечность**

в консольном - все работает.

**Comment by erastmorgan** [comment]
Привет, можешь отправить тестовый проект в котором не работает? проверю в
чем дело

2017-03-24 13:30 GMT+04:00 levkin77 <notifications@github.com>:

**Comment by levkin77** [comment]
[TESTMailRu.zip](https://github.com/erastmorgan/Mail.Ru-.net-cloud-client/files/867921/TESTMailRu.zip)

public ActionResult Index()
        {
            **string Login = "ttv@mail.ru";
            string Password = "***********";
            Account account = new Account(Login, Password);
            // не работает работает!!!!
            var res = account.Login();**
            return View();
        }

**Comment by levkin77** [comment]
При вызове в методе контроллера в MVC только так удалось заставить работать:
bool result = false;
**System.Threading.Tasks.Task.Run(() =>
{**
 MailRuCloudApi.Account account = new MailRuCloudApi.Account(value.Uid, value.Password);
 result = account.Login();
**}).GetAwaiter().GetResult();**
