### ISSUE TITLE
Апдейт?

### ISSUE THREAD

**Issue by Goldybin** [erastmorgan/Mail.Ru-.net-cloud-client#9]
Добрый день,
спасибо за написание данного кода! К сожалению не смог никак "заставить" работать в VS2017 - на этапе логина "подвисает" и все. Изменилась структура вызовов или что-то другое? Спасибо!

**Comment by vitidev** [comment]
Я пытался написать более современный вариант библиотеки, но это кошмар. Я уперся в 400 Bad Request при заливке файла, а остальное работает. Но фаза логина удачно пройдена и если что править в этой библиотеке то класс Account в LoginAsync должно быть так

      string reqString = string.Format("Login={0}&Domain={1}&Password={2}&FailPage&page=https://cloud.mail.ru/?new_auth_form=1", this.LoginName, ConstSettings.Domain, HttpUtility.UrlEncode(this.Password));
     byte[] requestData = Encoding.UTF8.GetBytes(reqString);
     var request = (HttpWebRequest)WebRequest.Create(string.Format("{0}/cgi-bin/auth?from=splash", ConstSettings.AuthDomen));

**Comment by mediaexplorer74** [comment]
>[vitidev](https://github.com/vitidev) 
>Я пытался написать более современный вариант библиотеки, но это кошмар. Я уперся в 400 Bad Request при заливке файла, а остальное работает. Но фаза логина удачно пройдена и если что править в этой библиотеке то класс Account в LoginAsync должно быть так
> 
> ```
>   string reqString = string.Format("Login={0}&Domain={1}&Password={2}&FailPage&page=https://cloud.mail.ru/?new_auth_form=1", this.LoginName, ConstSettings.Domain, HttpUtility.UrlEncode(this.Password));
>  byte[] requestData = Encoding.UTF8.GetBytes(reqString);
>  var request = (HttpWebRequest)WebRequest.Create(string.Format("{0}/cgi-bin/auth?from=splash", ConstSettings.AuthDomen));
> ```

Прювет, пустя 7 лет. Интересно, однако. А Вашей версии библиотечки не осталось случайно? И какой-нить тестовой приложеньки (в идеале UWP). Просто я ретроман, хотел бы простенькую софтинку MailRuCloud для старенького финфончика сляпать))

**Comment by erastmorgan** [comment]
> > Я пытался написать более современный вариант библиотеки, но это кошмар. Я уперся в 400 Bad Request при заливке файла, а остальное работает. Но фаза логина удачно пройдена и если что править в этой библиотеке то класс Account в LoginAsync должно быть так
> > ```
> >   string reqString = string.Format("Login={0}&Domain={1}&Password={2}&FailPage&page=https://cloud.mail.ru/?new_auth_form=1", this.LoginName, ConstSettings.Domain, HttpUtility.UrlEncode(this.Password));
> >  byte[] requestData = Encoding.UTF8.GetBytes(reqString);
> >  var request = (HttpWebRequest)WebRequest.Create(string.Format("{0}/cgi-bin/auth?from=splash", ConstSettings.AuthDomen));
> > ```
> 
> Прювет, пустя 7 лет. Интересно, однако. А Вашей версии библиотечки не осталось случайно? И какой-нить тестовой приложеньки (в идеале UWP). Просто я ретроман, хотел бы простенькую софтинку MailRuCloud для старенького финфончика сляпать))

Данная либа уже давно не актуализировалась, все что есть на гитхабе выложено. Локально каких-либо иных версий или программ по ее использованию не осталось, хотя и были когда-то.

**Comment by mediaexplorer74** [comment]
> > > Я пытался написать более современный вариант библиотеки, но это кошмар. Я уперся в 400 Bad Request при заливке файла, а остальное работает. Но фаза логина удачно пройдена и если что править в этой библиотеке то класс Account в LoginAsync должно быть так
> > > ```
> > >   string reqString = string.Format("Login={0}&Domain={1}&Password={2}&FailPage&page=https://cloud.mail.ru/?new_auth_form=1", this.LoginName, ConstSettings.Domain, HttpUtility.UrlEncode(this.Password));
> > >  byte[] requestData = Encoding.UTF8.GetBytes(reqString);
> > >  var request = (HttpWebRequest)WebRequest.Create(string.Format("{0}/cgi-bin/auth?from=splash", ConstSettings.AuthDomen));
> > > ```
> > 
> > 
> > Прювет, пустя 7 лет. Интересно, однако. А Вашей версии библиотечки не осталось случайно? И какой-нить тестовой приложеньки (в идеале UWP). Просто я ретроман, хотел бы простенькую софтинку MailRuCloud для старенького финфончика сляпать))
> 
> Данная либа уже давно не актуализировалась, все что есть на гитхабе выложено. Локально каких-либо иных версий или программ по ее использованию не осталось, хотя и были когда-то.

Здравствуйте. Большое спасибо за быстрый авторский ответ и ценные замечания. Так понял, эта либа не донтнеткоровская, а именно дотнетсандартовская (.net 1.6 ?) Прям то, что нужно для кросс-платформы. Ну, изменения в API да, наверняка требуется изучить и добавить. Нет цели 1001 фичу реализовывать, чисто автозаливку фоток с Люмки в Облако через фоновую задачу хотел бы залудить, да, и пожалуй, стопорнуться

**Comment by mediaexplorer74** [comment]
> [CoderCoderCoder](https://github.com/CoderCoderCoder)
>Добрый день,
>спасибо за написание данного кода! К сожалению не смог никак "заставить" работать в VS2017 - на этапе логина >"подвисает" и все. Изменилась структура вызовов или что-то другое? Спасибо!

Оно не то что бы "подвисает", скорей "циклит" либо "вылетает". :(  Думаю, не столько в изменении api дело (хотя где-то уже да, не v2 , а v4, спустя годы), сколько в злоупотреблении асинхронностью вызовов функций и отсутствием защитных try...catch. Пытаюсь [разобраться](https://github.com/mediaexplorer74/MailRuCloudNET), хоть и вовсе не c# прогер (это чисто хобби, так сказать)
